spring:
  config:
    import: "file:${scan.config}/scan-application.yml"

scan:
  # sample value, should be overridden in Spring command line properties, e.g. -Dscan.project=/work/project/scan-sample
  project: scan-project/sample
  # "replace" - mask, "restore" - unmask, e.g. -Dscan.direction=restore
  direction: replace
  config: "${scan.project}/config"
  target: ${scan.project}/target

read:
  threads: 10

replace:
  defaultTemplate: "w{hash}"
  report: ${scan.target}/replace-report.csv
  restoreInstructionCumulative: ${scan.target}/restore-instruction-cumulative.csv
  restoreInstructionLast: ${scan.target}/restore-instruction-last.csv
  generatedReplacement: ${scan.target}/generated-replacement.csv
  fileError: ${scan.target}/file-error.csv

restore:
  report: ${scan.target}/restore-report.csv
  generatedReplacement: ${scan.target}/restore-generated-replacement.csv
  fileError: ${scan.target}/restore-file-error.csv

write:
  # Default is Review phase (false). After review is completed, to Cleanup Code add JVM parameter -Dwrite.inplace=true
  inplace: false
  folder: ${scan.target}/preview

csv:
  dictionaryCandidate: ${scan.target}/csv-dictionary-candidate.csv

logging:
  file: ${scan.target}/logs/code-egress.log